/**
 * Copy style guard.
 *
 * The project owner has banned the em dash from project-authored content: not
 * from the rendered product only, but from documentation, comments, QA
 * messages and commit-adjacent canonical text as well. This is the check that
 * keeps it out once it has been removed.
 *
 *   node qa/copy-style.mjs
 *
 * It reads the tracked file list from git, so it sees exactly what would be
 * published and nothing that would not. Binary files are skipped by extension
 * and then again by content, and `package-lock.json` is skipped because it is
 * generated by npm rather than written here.
 *
 * The banned character is built from its codepoint rather than typed, so this
 * file does not fail the rule it enforces.
 */

import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";

const EM_DASH = String.fromCharCode(0x2014);

/** Generated or third-party content this project does not author. */
const NOT_OURS = [/^package-lock\.json$/, /(^|\/)node_modules\//];

const BINARY_EXT =
  /\.(png|jpe?g|gif|webp|ico|svg|woff2?|ttf|otf|eot|pdf|zip|gz|mp4|webm|bundle)$/i;

let failures = 0;
let checks = 0;
const check = (label, ok, detail = "") => {
  checks += 1;
  if (!ok) failures += 1;
  console.log(`  ${ok ? "PASS" : "FAIL"}  ${label.padEnd(52)}${detail ? "  " + detail : ""}`);
};

const tracked = execFileSync("git", ["ls-files"], { encoding: "utf8", maxBuffer: 64 * 1024 * 1024 })
  .split("\n")
  .filter(Boolean)
  .filter((p) => !BINARY_EXT.test(p))
  .filter((p) => !NOT_OURS.some((re) => re.test(p)));

console.log(`\n########## COPY STYLE ##########`);
console.log(`  ${tracked.length} tracked text files scanned`);

const hits = [];
for (const path of tracked) {
  let text;
  try {
    text = readFileSync(path, "utf8");
  } catch {
    continue;
  }
  /* A NUL byte means the extension list missed a binary. */
  if (text.includes(String.fromCharCode(0))) continue;
  if (!text.includes(EM_DASH)) continue;

  text.split("\n").forEach((line, i) => {
    if (!line.includes(EM_DASH)) return;
    const column = line.indexOf(EM_DASH) + 1;
    /* The offending line is shown with the character replaced, so the report
       itself stays clean. */
    hits.push(`${path}:${i + 1}:${column}  ${line.trim().replace(new RegExp(EM_DASH, "g"), "[EM DASH]").slice(0, 88)}`);
  });
}

check("no em dash in tracked project text", hits.length === 0, `${hits.length} occurrence(s)`);

if (hits.length > 0) {
  console.log("\n  Replace each with punctuation chosen for meaning - a colon where what");
  console.log("  follows explains, a comma for an aside, a full stop between two");
  console.log("  sentences, parentheses around a bracketed clause, a hyphen in a");
  console.log("  heading. Do not substitute the same character everywhere.\n");
  for (const hit of hits.slice(0, 40)) console.log(`    ${hit}`);
  if (hits.length > 40) console.log(`    ... and ${hits.length - 40} more`);
}

console.log(
  `\n=== copy style: ${failures === 0 ? `ALL PASS (${checks} checks)` : `${failures} FAILURE(S) of ${checks}`} ===`
);
process.exit(failures === 0 ? 0 : 1);
